CONFIG_LEGACY_GENERATED_INCLUDE_PATH=n

CONFIG_MAIN_STACK_SIZE=2048

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_EARLY_CONSOLE=y

CONFIG_DISPLAY=y
CONFIG_ST7789V=y

CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_PINCTRL_ESP32=y

# PWM Support for backlight control
CONFIG_PWM=y
CONFIG_PWM_LED_ESP32=y

# CONFIG_SPI is not set
# CONFIG_SPI_ASYNC is not set
# CONFIG_ESP32_SPIM is not set
# CONFIG_SPI_ESP32_INTERRUPT is not set

# CONFIG_BOOT_BANNER is not set
# CONFIG_SPI_FLASH_SUPPORT_ISSI_CHIP is not set
# CONFIG_SPI_FLASH_SUPPORT_MXIC_CHIP is not set
# CONFIG_SPI_FLASH_SUPPORT_GD_CHIP is not set
CONFIG_SPI_FLASH_SUPPORT_WINBOND_CHIP=y
# CONFIG_SPI_FLASH_SUPPORT_BOYA_CHIP is not set
# CONFIG_SPI_FLASH_SUPPORT_TH_CHIP is not set
# CONFIG_SPI_FLASH_SUPPORT_MXIC_OPI_CHIP is not set
# CONFIG_SPI_FLASH_ROM_DRIVER_PATCH is not set

CONFIG_DMA=y
CONFIG_DMA_ESP32_MAX_DESCRIPTOR_NUM=128

CONFIG_ESPTOOLPY_FLASHMODE_QIO=y
CONFIG_ESPTOOLPY_FLASHFREQ_80M=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_XIP=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_CACHE=y

CONFIG_ESPTOOLPY_HEADER_FLASHSIZE_UPDATE=y
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

CONFIG_POSIX_THREADS=y
CONFIG_POSIX_SYSTEM_INTERFACES=y

CONFIG_DEBUG=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_DEBUG_OPTIMIZATIONS=y
# CONFIG_DEBUG_COREDUMP is not set

# Enable debug logging for MIPI DBI driver
CONFIG_MIPI_DBI_LOG_LEVEL_DBG=y
CONFIG_LOG_MAX_LEVEL=4